### ISSUE TITLE
Hubs "remember" member_key of re-used badges

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub-py#36]
If a badge (mac address) is reused in the system (assigned to a different member), the hubs will still remember the member_key of the old member.

Reason - the hubs "cache" badges info in a key store, where the key is the mac address. There's a functions that updates the info from the server, but it does not update the member_key (only some of the other fields).

**Comment by jordanreedie** [comment]
per our discussion, i'm going to check to see if there's a specific reason we're caching the member key. If not, I'll remove caching entirely
